export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const SIGNUP_EMAIL_REQUEST = 'SIGNUP_EMAIL_REQUEST'
export const SIGNUP_EMAIL_FAILURE = 'SIGNUP_EMAIL_FAILURE'
export const SIGNUP_EMAIL_SUCCESS = 'SIGNUP_EMAIL_SUCCESS'

export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST'
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE'
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS'

export const GOOGLE_LOGIN_AUTH_REQUEST = 'GOOGLE_LOGIN_AUTH_REQUEST'
export const GOOGLE_LOGIN_AUTH_FAILURE = 'GOOGLE_LOGIN_AUTH_FAILURE'
export const GOOGLE_LOGIN_AUTH_SUCCESS = 'GOOGLE_LOGIN_AUTH_SUCCESS'

export const VERIFY_INVITE_USER_REQUEST = 'VERIFY_INVITE_USER_REQUEST'
export const VERIFY_INVITE_USER_FAILURE = 'VERIFY_INVITE_USER_FAILURE'
export const VERIFY_INVITE_USER_SUCCESS = 'VERIFY_INVITE_USER_SUCCESS'

export const SIGNUP_INVITE_USER_REQUEST = 'SIGNUP_INVITE_USER_REQUEST'
export const SIGNUP_INVITE_USER_FAILURE = 'SIGNUP_INVITE_USER_FAILURE'
export const SIGNUP_INVITE_USER_SUCCESS = 'SIGNUP_INVITE_USER_SUCCESS'

export const LOGOUT_USER = 'LOGOUT_USER'
