export const MASTER_DATA_REQUEST = 'MASTER_DATA_REQUEST'
export const MASTER_DATA_FAILURE = 'MASTER_DATA_FAILURE'
export const MASTER_DATA_SUCCESS = 'MASTER_DATA_SUCCESS'

export const ORGANIZATION_LIST_REQUEST = 'ORGANIZATION_LIST_REQUEST'
export const ORGANIZATION_LIST_FAILURE = 'ORGANIZATION_LIST_FAILURE'
export const ORGANIZATION_LIST_SUCCESS = 'ORGANIZATION_LIST_SUCCESS'


