export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
