export const GET_ORGANIZATION_REQUEST = 'GET_ORGANIZATION_REQUEST'
export const GET_ORGANIZATION_FAILURE = 'GET_ORGANIZATION_FAILURE'
export const GET_ORGANIZATION_SUCCESS = 'GET_ORGANIZATION_SUCCESS'

export const UPDATE_ORGANIZATION_REQUEST = 'UPDATE_ORGANIZATION_REQUEST'
export const UPDATE_ORGANIZATION_FAILURE = 'UPDATE_ORGANIZATION_FAILURE'
export const UPDATE_ORGANIZATION_SUCCESS = 'UPDATE_ORGANIZATION_SUCCESS'

export const GET_CHARTS_ACCOUNT_REQUEST = 'GET_CHARTS_ACCOUNT_REQUEST'
export const GET_CHARTS_ACCOUNT_FAILURE = 'GET_CHARTS_ACCOUNT_FAILURE'
export const GET_CHARTS_ACCOUNT_SUCCESS = 'GET_CHARTS_ACCOUNT_SUCCESS'

export const ADD_CHARTS_ACCOUNT_REQUEST = 'ADD_CHARTS_ACCOUNT_REQUEST'
export const ADD_CHARTS_ACCOUNT_FAILURE = 'ADD_CHARTS_ACCOUNT_FAILURE'
export const ADD_CHARTS_ACCOUNT_SUCCESS = 'ADD_CHARTS_ACCOUNT_SUCCESS'

export const UPDATE_CHARTS_ACCOUNT_REQUEST = 'UPDATE_CHARTS_ACCOUNT_REQUEST'
export const UPDATE_CHARTS_ACCOUNT_FAILURE = 'UPDATE_CHARTS_ACCOUNT_FAILURE'
export const UPDATE_CHARTS_ACCOUNT_SUCCESS = 'UPDATE_CHARTS_ACCOUNT_SUCCESS'

export const GET_VAT_CODES_REQUEST = 'GET_VAT_CODES_REQUEST'
export const GET_VAT_CODES_FAILURE = 'GET_VAT_CODES_FAILURE'
export const GET_VAT_CODES_SUCCESS = 'GET_VAT_CODES_SUCCESS'

export const ADD_VAT_CODES_REQUEST = 'ADD_VAT_CODES_REQUEST'
export const ADD_VAT_CODES_FAILURE = 'ADD_VAT_CODES_FAILURE'
export const ADD_VAT_CODES_SUCCESS = 'ADD_VAT_CODES_SUCCESS'

export const UPDATE_VAT_CODES_REQUEST = 'UPDATE_VAT_CODES_REQUEST'
export const UPDATE_VAT_CODES_FAILURE = 'UPDATE_VAT_CODES_FAILURE'
export const UPDATE_VAT_CODES_SUCCESS = 'UPDATE_VAT_CODES_SUCCESS'

export const ADD_INVITE_USER_REQUEST = 'ADD_INVITE_USER_REQUEST'
export const ADD_INVITE_USER_FAILURE = 'ADD_INVITE_USER_FAILURE'
export const ADD_INVITE_USER_SUCCESS = 'ADD_INVITE_USER_SUCCESS'

export const ADD_ORGANIZATION_REQUEST = 'ADD_ORGANIZATION_REQUEST'
export const ADD_ORGANIZATION_FAILURE = 'ADD_ORGANIZATION_FAILURE'
export const ADD_ORGANIZATION_SUCCESS = 'ADD_ORGANIZATION_SUCCESS'

